application:
  title: Microservico Admin
  version: 1.0.0

# IMPORTANT! USADO PARA REGISTRO NO GATEWAY E LOADBALANCER
spring:
  application:
    name: msadmin

  # CONFIGURACOES DO SERVICO RABBITMQ
  rabbitmq:
    host: ${RABBITMQ_SERVER}
    port: ${RABBITMQ_SERVER_PORT}
    user: guest
    password: guest

# vai subir o microservico em uma porta randomica ao inves da 8080
# dentro do eureka server
server:
  port: 0

# indicar ao cliente para apontar para configuracoes do eurika server
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER}:${EUREKA_SERVER_PORT}/eureka
  # instanceid no eurika de forma dinamica no dashboard
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

# definicao das filas e exchanges que este projeto ira interagir

mq:
  queues:
    admin: admin.input
    handshake: mensageiro.handshake.input
  exchanges:
    ms:
      direct:
        exchangeDefault: exchange-default.input
  routingKey:
    mensageiroHandshake: mensageiro.handshakeRK