spring:
  application:
    name: msclientes

# vai subir o microservico em uma porta randomica ao inves da 8080
# dentro do eureka server
server:
  port: 0

# indicar ao cliente para apontar para configuracoes do eurika server
eurika:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# instanceid no eurika de forma dinamica no dashboard
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
