application:
  title: Cloud Gateway for MS Microservices project
  version: 1.0.0

# IMPORTANT! USADO PARA REGISTRO NO GATEWAY E LOADBALANCER
spring:
  application:
    name: ms-cloud-gateway

  # habilita do cloud gateway para interceptar e direcionar chamadas para o eurika loadbalancer
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# configura porta padrao de recebimento das requisicoes no gateway
server:
  port: 8080

# configura as informacoes de como o cloud gateway vai encontrar o eurika
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_SERVER}:8761/eureka



